# Generated by Django 4.1.7 on 2023-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        default="No Description",
                        max_length=2000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("image", models.CharField(max_length=2000, verbose_name="Image")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("other", "Разное"),
                            ("food", "Еда"),
                            ("pharmacy", "Аптека"),
                            ("car", "Авто"),
                            ("device", "Гаджеты"),
                        ],
                        default="other",
                        max_length=40,
                        verbose_name="Category",
                    ),
                ),
                ("balance", models.IntegerField(verbose_name="Balance")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Price"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and time created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date and time updated"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
    ]
