# Generated by Django 4.1.7 on 2023-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("food", "Food"),
                    ("pharmacy", "Pharmacy"),
                    ("car", "Car"),
                    ("device", "Device"),
                ],
                default="other",
                max_length=40,
                verbose_name="Category",
            ),
        ),
    ]
