# Generated by Django 4.1.7 on 2023-02-27 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online_store", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="balance",
            field=models.IntegerField(
                default=None,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Balance",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.TextField(
                choices=[
                    ("other", "Other"),
                    ("food", "Food"),
                    ("pharmacy", "Pharmacy"),
                    ("car", "Car"),
                    ("device", "Device"),
                ],
                default="other",
                max_length=40,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.TextField(max_length=2000, verbose_name="Image"),
        ),
    ]
