# Generated by Django 4.1.7 on 2023-03-13 03:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_alter_product_deleted_at_alter_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Product', to='online_store.product')),
            ],
        ),
    ]
