# Generated by Django 4.1.7 on 2023-03-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_productincart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInCart',
            new_name='Cart',
        ),
    ]
